### ISSUE TITLE
Missing required params, doesn't make the parser to fail

### ISSUE THREAD

**Issue by nemo83** [sellmerfud/optparse#6]
Hi, 

I have a quick question for you. I'm using this library and I've noticed that despite declaring a switch as required, the parser does not throw any exception if the switch is not passed on the cli.

eg.

`reqd[String]("-b", "--s3-bucket-name <s3_bucket_name>", "Specify a revision") { (v, cfg) => cfg.copy(s3BucketName = v) }`

But if I omit it, the cli still successfully processes the args. Is this the desired behaviour? 

Thanks

**Comment by sellmerfud** [comment]
The `reqd` function indicates that the **value** for the switch is required.  Not that the switch itself is required.

If a switch is required, then your code is responsible for enforcing this.

**Comment by nemo83** [comment]
Thanks for the clarifications.
